spring:
  profiles:
    default: local
  application:
    name: backend-thanos

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  server:
    port: 8080

  logging:
    level:
      org.springframework.web: INFO
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE